export const MAIN_LOG_MOUSE_MOVE = "MAIN_LOG_MOUSE_MOVE";

export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_ACTIVE_CONTENT = "SET_ACTIVE_CONTENT";
export const SET_DEV_USER_ID = "SET_DEV_USER_ID";

export const LOG_QUESTION_RESPONSE = "LOG_QUESTION_RESPONSE";
export const LOG_GENERAL_QUESTION_PAGE = "LOG_GENERAL_QUESTION_PAGE";

export const LOG_SURVEY_RESPONSE = "LOG_SURVEY_RESPONSE";
export const LOG_GENERAL_SURVEY_PAGE = "LOG_GENERAL_SURVEY_PAGE";
export const LOG_GENERAL_MOUSE_TASK = "LOG_GENERAL_MOUSE_TASK";

export const ADD_S3_EVENT = "ADD_S3_EVENT";
export const UPLOAD_PAGE_ON_MOUNT = "UPLOAD_PAGE_ON_MOUNT";

export const SET_PARTICIPANT_NUM = "SET_PARTICIPANT_NUM";