export const goodMovies = [
    {
      key: 1,
      name: "Shrek 2 (2004)",
      rating: 7.3,
      desc: "Shrek and Fiona travel to the Kingdom of Far Far Away, where Fiona's parents are King and Queen, to celebrate their marriage. When they arrive, they find they are not as welcome as they thought they would be.",
      image: require("../../assets/shrek2.jpg"),
    },
    {
      key: 2,
      name: "I Am Legend (2007)",
      rating: 7.2,
      desc: "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
      image: require("../../assets/legend.jpg"),
    },
    {
      key: 3,
      name: "Furious 7 (2015)",
      rating: 7.1,
      desc: "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
      image: require("../../assets/f7.jpg"),
    },
    {
      key: 4,
      name: "Wonder Woman (2017)",
      rating: 7.4,
      desc: "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
      image: require("../../assets/wonder.jpg"),
    },
    {
      key: 5,
      name: "The Lion King (2019)",
      rating: 6.8,
      desc: "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
      image: require("../../assets/lionking.jpg"),
    },
    {
      key: 6,
      name: "Beauty and the Beast (2017)",
      rating: 7.1,
      desc: "A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman he keeps prisoner.",
      image: require("../../assets/beauty.jpg"),
    },
    {
      key: 7,
      name: "It (2017)",
      rating: 7.3,
      desc: "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.",
      image: require("../../assets/it.jpg"),
    },
    {
      key: 8,
      name: "Harry Potter and the Order of the Phoenix (2007)",
      ratiing: 7.5,
      desc: "With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.",
      image: require("../../assets/hp.jpg"),
    },
    {
      key: 9,
      name: "Spider-Man: Homecoming (2017)",
      rating: 7.4,
      desc: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
      image: require("../../assets/homecoming.jpg"),
    },
    {
      key: 10,
      name: "The Hunger Games (2012)",
      rating: 7.2,
      desc: "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.",
      image: require("../../assets/hunger.jpg"),
    },
  ];


  export const badMovies = [
    {
      key: 1,
      name: "Catwoman (2004)",
      rating: 3.4,
      desc: "A shy woman, endowed with the speed, reflexes, and senses of a cat, walks a thin line between criminal and hero, even as a detective doggedly pursues her, fascinated by both of her personas.",
      image: require("../../assets/catwoman.jpg"),
    },
    {
      key: 2,
      name: "Scary Movie V (2013)",
      rating: 3.5,
      desc: "A couple begin to experience some unusual activity after bringing their lost nieces and nephew home. With the help of home-surveillance cameras, they learn they're being stalked by a nefarious demon.",
      image: require("../../assets/scary.jpg"),
    },
    {
      key: 3,
      name: "Rollerball (2002)",
      rating: 3.1,
      desc: "The big thing in 2005 is a violent sport which can have some pretty serious consequences... like dying. ",
      image: require("../../assets/rollerball.jpg"),
    },
    {
      key: 4,
      name: "Dragon Wars: D-War (2007)",
      rating: 3.5,
      desc: "Once in 500 years, ancient mythical creatures come to Earth, wreaking havoc and destruction. This time they must be stopped.",
      image: require("../../assets/dwar.jpg"),
    },
    {
      key: 5,
      name: "Mac and Me (1988)",
      rating: 3.3,
      desc: "An alien trying to escape from NASA is befriended by a wheelchair-bound boy.",
      image: require("../../assets/mac.jpg"),
    },
    {
      key: 6,
      name: "Dragonball Evolution (2009)",
      rating: 2.6,
      desc: "The young warrior Son Goku sets out on a quest, racing against time and the vengeful King Piccolo, to collect a set of seven magical orbs that will grant their wielder unlimited power.",
      image: require("../../assets/dragonball.jpg"),
    },
    {
      key: 7,
      name: "Dance Flick (2009)",
      rating: 3.5,
      desc: "Street dancer Thomas Uncles is from the wrong side of the tracks, but his bond with the beautiful Megan White might help the duo realize their dreams as they enter in the mother of all dance battles.",
      image: require("../../assets/dance.jpg"),
    },
    {
      key: 8,
      name: "The Emoji Movie (2017)",
      rating: 3.3,
      desc: "Gene, a multi-expressional emoji, sets out on a journey to become a normal emoji.",
      image: require("../../assets/emoji.jpg"),
    },
    {
      key: 9,
      name: "Date Movie (2006)",
      rating: 2.8,
      desc: "Spoof of romantic comedies which focuses on a man, his crush, his parents, and her father.",
      image: require("../../assets/date.jpg"),
    },
    {
      key: 10,
      name: "Vampires Suck (2010)",
      rating: 3.4,
      desc: "A spoof of vampire-themed movies. Teenager, Becca finds herself torn between 2 boys. As she and her friends wrestle with a number of different dramas, everything comes to a head at their prom.",
      image: require("../../assets/vamp.jpg"),
    },
  ];